// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtPekbaGDWnAYgcd610_tNMA8IL3DjVLU',
    appId: '1:109777665072:web:7bd55b6ae3747b412301f5',
    messagingSenderId: '109777665072',
    projectId: 'smart-expense-tracker-82ac2',
    authDomain: 'smart-expense-tracker-82ac2.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-82ac2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFuwSS16wPGkLqKLT4CFPmN15vaNlbgA0',
    appId: '1:109777665072:android:44152d0e518a291d2301f5',
    messagingSenderId: '109777665072',
    projectId: 'smart-expense-tracker-82ac2',
    storageBucket: 'smart-expense-tracker-82ac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY2HRPB0hwLbOJ9HVwUjsyVO_5WJBCFqo',
    appId: '1:109777665072:ios:d8dc349f56e7af502301f5',
    messagingSenderId: '109777665072',
    projectId: 'smart-expense-tracker-82ac2',
    storageBucket: 'smart-expense-tracker-82ac2.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY2HRPB0hwLbOJ9HVwUjsyVO_5WJBCFqo',
    appId: '1:109777665072:ios:d8dc349f56e7af502301f5',
    messagingSenderId: '109777665072',
    projectId: 'smart-expense-tracker-82ac2',
    storageBucket: 'smart-expense-tracker-82ac2.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtPekbaGDWnAYgcd610_tNMA8IL3DjVLU',
    appId: '1:109777665072:web:14ff20a3f7d0ddd72301f5',
    messagingSenderId: '109777665072',
    projectId: 'smart-expense-tracker-82ac2',
    authDomain: 'smart-expense-tracker-82ac2.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-82ac2.firebasestorage.app',
  );
}
